## 1. Import the libraries et data

In [1]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("Airbnb_Paris_Rawdata.csv")
df.head(5)

,address,location/lat,location/lng,name,numberOfGuests,pricing/rate/amount,pricing/rate/amount_formatted,pricing/rate/currency,pricing/rate/is_micros_accuracy,pricing/rate_type,pricing/rate_with_service_fee/amount,pricing/rate_with_service_fee/amount_formatted,pricing/rate_with_service_fee/currency,pricing/rate_with_service_fee/is_micros_accuracy,roomType,stars,url,Unnamed: 17,Unnamed: 18
0,"Paris, Ile-de-France, France",48.86406,2.28492,Tres Chic Trocadero Garden,6,6050,NaN,EUR,FALSE,nightly,6050,NaN,EUR,FALSE,Entire villa,NaN,https://www.airbnb.com/rooms/20471160,NaN,NaN
1,"Paris, Ile-de-France, France",48.867,2.304,Sweet Inn | Exclusive duplex near the Champs-E...,12,5040,NaN,EUR,FALSE,nightly,5040,NaN,EUR,FALSE,Entire rental unit,4.5,https://www.airbnb.com/rooms/41186444,NaN,NaN
2,"Paris, Ile-de-France, France",48.868,2.333,Hotel Edouard 7,0,9000,NaN,EUR,FALSE,nightly,9000,NaN,EUR,FALSE,Room in boutique hotel,NaN,https://www.airbnb.com/rooms/43095866,NaN,NaN
3,"Paris, Ile-de-France, France",48.874,2.358,"Center Paris, Cozy 85 sqm, 7 min walk to Le Ma...",6,8000,NaN,EUR,FALSE,nightly,8000,NaN,EUR,FALSE,Entire rental unit,5,https://www.airbnb.com/rooms/33383936,NaN,NaN
4,"Paris, Ile-de-France, France",48.876,2.295,"Chambre Solo, Magda Champs Elysees",1,9000,NaN,EUR,FALSE,nightly,9000,NaN,EUR,FALSE,Room in boutique hotel,NaN,https://www.airbnb.com/rooms/42658975,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14497 entries, 0 to 14496
Data columns (total 19 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   address                                           14497 non-null  object
 1   location/lat                                      14496 non-null  object
 2   location/lng                                      14493 non-null  object
 3   name                                              14456 non-null  object
 4   numberOfGuests                                    14450 non-null  object
 5   pricing/rate/amount                               13606 non-null  object
 6   pricing/rate/amount_formatted                     41 non-null     object
 7   pricing/rate/currency                             13609 non-null  object
 8   pricing/rate/is_micros_accuracy                   13572 non-null  object
 9   pricing/rate_type                                 13608 non-null  object
 10  pricing/rate_with_service_fee/amount              13606 non-null  object
 11  pricing/rate_with_service_fee/amount_formatted    42 non-null     object
 12  pricing/rate_with_service_fee/currency            13604 non-null  object
 13  pricing/rate_with_service_fee/is_micros_accuracy  13609 non-null  object
 14  roomType                                          14413 non-null  object
 15  stars                                             12520 non-null  object
 16  url                                               14411 non-null  object
 17  Unnamed: 17                                       1 non-null      float64
 18  Unnamed: 18                                       1 non-null      object
dtypes: float64(1), object(18)
memory usage: 2.1+ MB

In [ ]:
##Change le type of data

df["numberOfGuests"] = df["numberOfGuests"].astype('int')

df["pricing/rate/amount"] = df["pricing/rate/amount"].astype('float')
df["pricing/rate_with_service_fee/amount"] = df["pricing/rate_with_service_fee/amount"].astype('float')

## 2. Delete useless columns

In [13]:
df["pricing/rate/currency"].value_counts()

EUR        13568
FALSE          3
135            2
88             2
69             2
81             1
54             1
93             1
67             1
79             1
73             1
83             1
56             1
95             1
59             1
70             1
62             1
63             1
80             1
49             1
48             1
92             1
400            1
94             1
102            1
190            1
191            1
126            1
nightly        1
114            1
117            1
109            1
37             1
170            1
29             1
22             1
61             1
Name: pricing/rate/currency, dtype: int64

In [14]:
df["pricing/rate/is_micros_accuracy"].value_counts()

FALSE      13568
nightly        3
105            1
Name: pricing/rate/is_micros_accuracy, dtype: int64

In [15]:
df["pricing/rate_with_service_fee/currency"].value_counts()

EUR                   13568
5                        16
4.5                      13
FALSE                     3
4                         2
Entire rental unit        1
95                        1
Name: pricing/rate_with_service_fee/currency, dtype: int64

In [16]:
df["pricing/rate_with_service_fee/is_micros_accuracy"].value_counts()

FALSE                                    13568
Entire rental unit                           2
https://www.airbnb.com/rooms/36251138        1
https://www.airbnb.com/rooms/53744405        1
https://www.airbnb.com/rooms/26481203        1
https://www.airbnb.com/rooms/42529937        1
https://www.airbnb.com/rooms/54337133        1
https://www.airbnb.com/rooms/24804703        1
https://www.airbnb.com/rooms/43846451        1
https://www.airbnb.com/rooms/48241794        1
https://www.airbnb.com/rooms/19559817        1
https://www.airbnb.com/rooms/51273991        1
https://www.airbnb.com/rooms/11691078        1
https://www.airbnb.com/rooms/51497251        1
https://www.airbnb.com/rooms/51955041        1
https://www.airbnb.com/rooms/52153662        1
https://www.airbnb.com/rooms/12719437        1
https://www.airbnb.com/rooms/29844394        1
https://www.airbnb.com/rooms/52486737        1
https://www.airbnb.com/rooms/43941179        1
https://www.airbnb.com/rooms/36905103        1
https://www.airbnb.com/rooms/35731585        1
https://www.airbnb.com/rooms/42667568        1
https://www.airbnb.com/rooms/11248960        1
https://www.airbnb.com/rooms/52468537        1
https://www.airbnb.com/rooms/50367957        1
https://www.airbnb.com/rooms/19205026        1
https://www.airbnb.com/rooms/47923498        1
https://www.airbnb.com/rooms/54164904        1
Private room in rental unit                  1
https://www.airbnb.com/rooms/6324741         1
https://www.airbnb.com/rooms/49212333        1
https://www.airbnb.com/rooms/50794899        1
https://www.airbnb.com/rooms/52176512        1
4.5                                          1
https://www.airbnb.com/rooms/53856929        1
https://www.airbnb.com/rooms/50718122        1
https://www.airbnb.com/rooms/36362082        1
https://www.airbnb.com/rooms/52047522        1
https://www.airbnb.com/rooms/32999409        1
https://www.airbnb.com/rooms/50805147        1
Name: pricing/rate_with_service_fee/is_micros_accuracy, dtype: int64

In [19]:
drop_list=["pricing/rate/amount_formatted", "pricing/rate/currency", "pricing/rate/is_micros_accuracy", "pricing/rate_with_service_fee/amount_formatted", "pricing/rate_with_service_fee/is_micros_accuracy","Unnamed: 17","Unnamed: 18" ]
df=df.drop(drop_list,axis=1)
df.head(5)

,address,location/lat,location/lng,name,numberOfGuests,pricing/rate/amount,pricing/rate_type,pricing/rate_with_service_fee/amount,pricing/rate_with_service_fee/currency,roomType,stars,url
0,"Paris, Ile-de-France, France",48.86406,2.28492,Tres Chic Trocadero Garden,6,6050,nightly,6050,EUR,Entire villa,NaN,https://www.airbnb.com/rooms/20471160
1,"Paris, Ile-de-France, France",48.867,2.304,Sweet Inn | Exclusive duplex near the Champs-E...,12,5040,nightly,5040,EUR,Entire rental unit,4.5,https://www.airbnb.com/rooms/41186444
2,"Paris, Ile-de-France, France",48.868,2.333,Hotel Edouard 7,0,9000,nightly,9000,EUR,Room in boutique hotel,NaN,https://www.airbnb.com/rooms/43095866
3,"Paris, Ile-de-France, France",48.874,2.358,"Center Paris, Cozy 85 sqm, 7 min walk to Le Ma...",6,8000,nightly,8000,EUR,Entire rental unit,5,https://www.airbnb.com/rooms/33383936
4,"Paris, Ile-de-France, France",48.876,2.295,"Chambre Solo, Magda Champs Elysees",1,9000,nightly,9000,EUR,Room in boutique hotel,NaN,https://www.airbnb.com/rooms/42658975

## 3. Delete outliers

In [ ]:
stats = df.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']

In [ ]:
outliers = pd.DataFrame(columns=df.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data[(data[col] < lower) | 
                   (data[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)

## delete outiliers of the columns "numberOfGuests"
outliers_delete=outliers[outliers.Outlier == "numberOfGuests"]
df=df[~df.loc[:,'name'].isin(outliers_delete["name"])]

## 4. Finding and Removing Duplicates

In [ ]:
df = df.drop_duplicates()

## 5. Export the data

In [ ]:
df.to_csv"Airbnb_Paris_Clean.csv"